### ISSUE TITLE
iOS / iPhone Devices - can't copy and paste digital signature

### ISSUE THREAD

**Issue by miketwenty1** [jdogresorg/freewallet-mobile#24]
There doesn't seem to be a way to copy a signed message off the app when signing an arbitrary message. This is only an issue on iPhone device. 
Long Press doesn't work. No apparent copy button.

**Comment by jdogresorg** [comment]
Thanks for the heads up on this. I'll make sure to add a 'Copy' button or some other way to make it very simple to copy a message signature.

**Comment by broomez420** [comment]
Hello show me a what you can see please

**Comment by broomez420** [comment]
How do I add other wallets seems I can only add btc wallets

**Comment by jdogresorg** [comment]
@broomez420 FreeWallet is a Bitcoin and Counterparty compatible wallet. Ie, it only works with Bitcoin, Counterparty, and Counterparty assets.

**Comment by broomez420** [comment]
Oh I applied to get my coin listed with you 😉

**Comment by miketwenty1** [comment]
honestly.. im confused why this conversation is happening in this enhancement request

**Comment by jdogresorg** [comment]
@broomez420 If you have any questions, please mail info@freewallet.io or join Counterparty slack at https://slack.counterparty.io. This area of github is for reporting technical issues with the software, not technical support and help :)

**Comment by jdogresorg** [comment]
I believe this has been fixed with 7d0b3b506b74b63636e28fdaa47e94cfad075e51 which should be live in app store shortly. Please reopen this issue if your still having an issue.
