### ISSUE TITLE
Private key client side handle

### ISSUE THREAD

**Issue by srezasm** [jdogresorg/freewallet-mobile#37]
![IMG_20211114_223302_695](https://user-images.githubusercontent.com/45644975/141694792-803286df-03df-4600-8355-6d25d8ee24fa.jpg)
What kind of client side private key handling is this that allows you to send whatever whomevers coin back?!

**Comment by jdogresorg** [comment]
Tis is an email from freewallet.org, which is a closed-source centralized wallet where you don't control the private keys.

Your getting that wallet confused with freewallet.io which is an OPEN source wallet where no one has access to your funds/keys except you.

You should talk to the freewallet.org guys about your concerns with their wallet... this email is not related in any way to freewallet.io or freewallet-mobile
