### ISSUE TITLE
Lock Token option missing

### ISSUE THREAD

**Issue by heunland** [jdogresorg/freewallet-mobile#6]
Add "Lock Token" option please to Token Issue screen. Also I would like an option to be able to lock the token in a separate transaction if I did not do it right away upon issuing the token,

**Comment by jdogresorg** [comment]
Also need to add the ability to issue additional issuances using the "create token" form.

**Comment by jdogresorg** [comment]
Featured added with 7d0b3b506b74b63636e28fdaa47e94cfad075e51
